### ISSUE TITLE
bas64 output not rendered properly.

### ISSUE THREAD

**Issue by MicahZoltu** [ChainSafe/simpleserialize.com#15]
If I choose `base64` as the `Output Type` it shows an array of numbers in the `Serialized` field.
![image](https://user-images.githubusercontent.com/886059/83851839-812ccb80-a745-11ea-94ba-a5f2a7677a27.png)

**Comment by 3xtr4t3rr3str14l** [comment]
just pushed a fix for this.  please test.

**Comment by MicahZoltu** [comment]
Output looks different, I assume that means it is fixed!  🎉
