### ISSUE TITLE
Ship sourcemaps.

### ISSUE THREAD

**Issue by MicahZoltu** [ChainSafe/simpleserialize.com#16]
I was going to go and figure out the solution to #15 and submit a PR, but the code deployed to https://simpleserialize.com/ is bundled and minified and doesn't include source maps.

Really, for a tiny demo site like this I feel like bundling and minification is totally not worth it.  You may improve page load time from 200ms to 100ms (very optimistic) which no human is going to notice, and in exchange it is harder for third party developers to poke around at your code.

**Comment by 3xtr4t3rr3str14l** [comment]
just pushed a fix for this. please test.

**Comment by MicahZoltu** [comment]
Looks good!
