### ISSUE TITLE
workerize-loader and webpack 5

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/simpleserialize.com#41]
The `workerize-loader` plugin that we are using does not support webpack 5 (pkg issue tracked here: https://github.com/developit/workerize-loader/issues/77).  So we have to use webpack 4 for now.  It also doesn't look like the package is being maintained much as this issue has been outstanding for a while despite there being 2 PRs in the package repo to solve the issue.

We could:
1) wait for the workerize-loader issue to be resolved
2) find a fork of workerize-loader that supports webpack 5
3) replace workerize-loader with something else that does the same thing
4) ???

**Comment by dapplion** [comment]
I would try 

> replace workerize-loader with something else that does the same thing
