### ISSUE TITLE
Option to display base64

### ISSUE THREAD

**Issue by terencechain** [ChainSafe/simpleserialize.com#5]
Can we add an option to display in base64 instead hex?

Instead of `toString('hex')`, we want `toString('base64')` here: https://github.com/ChainSafe/simpleserialize.com/blob/49679b842660e5a62afb270aff39fc04e881ca54/src/components/Serialize.tsx#L39

**Comment by prestonvanloon** [comment]
Please

**Comment by GregTheGreek** [comment]
@stalebot please mark stale

**Comment by prestonvanloon** [comment]
We want base64 input/output. It would be more convenient than having to convert to hex.

**Comment by GregTheGreek** [comment]
yeah ill look into it!

**Comment by GregTheGreek** [comment]
#6 closes this.

**Comment by wemeetagain** [comment]
one more PR #7

**Comment by wemeetagain** [comment]
Ok, byte arrays can now be input as both hex and base64 strings. (including the ssz input)
Also, sszed and hashTreeRooted output can be toggled between hex and base64. :)
